# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9722c5a417baa7870da6e546591d17270dbde73b1c0f56626f65513205532c13afa80b3890c7bd82f90d61cdfa02fd32a547b59d3c01bd255cd106a781b99861

test:
  secret_key_base: 5548f11a99f3f54133df9fc294d8c8243d6d59b9bf70217f08b36c90c05e6a5482bb1d2f94361cdffa2dce98b8cfb7d24cb2f111f9e532058407b5a45428f3c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
